Properly override respond_to? in Raindrops::Middleware::Proxy
Correct method definition according to Ruby documentation (https://ruby-doc.org/core-2.4.1/Object.html#method-i-respond_to-3F) is:

    respond_to?(string, include_all=false) → true or false

Rack started using second argument starting from version 2:

https://github.com/rack/rack/blob/master/lib/rack/body_proxy.rb#L14

If raindrops is used in Rack 2+ applications, an exception is raised:

    ArgumentError: wrong number of arguments (2 for 1)
        <ROOT>/gems/raindrops-0.18.0/lib/raindrops/middleware/proxy.rb:30:in `respond_to?'
        <ROOT>/gems/rack-2.0.3/lib/rack/body_proxy.rb:14:in `respond_to?'